---
- name: IIS Application Pool
  hosts: all
 
  tasks:

  - name: Performing  action on {{ app_pool_name }} application pool
    win_iis_webapppool:
      name: "{{ app_pool_name }}"
      state: "{{ accion }}"
